// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepositoryLayer;

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221128104047_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DomainLayer.Models.ChucDanh", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CreatedDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("TenChucDanh")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("TenChucDanh");

                    b.HasKey("Id")
                        .HasName("pk_chucdanhid");

                    b.ToTable("ChucDanh");
                });

            modelBuilder.Entity("DomainLayer.Models.ChucVu", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CreatedDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("TenChucVu");

                    b.HasKey("Id")
                        .HasName("pk_chucvuid");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("DomainLayer.Models.NhanVien", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("Id");

                    b.Property<string>("ChucDanh_ID")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("ChucDanh_ID");

                    b.Property<string>("ChucVu_ID")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("ChucVu_ID");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("FirstName");

                    b.Property<string>("Image")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("Image");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("LastName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("PhongBan_ID")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("PhongBan_ID");

                    b.HasKey("Id")
                        .HasName("pk_nhanvienid");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("DomainLayer.Models.PhongBan", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CreatedDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("TenPhongBan");

                    b.HasKey("Id")
                        .HasName("pk_phongbanid");

                    b.ToTable("PhongBan");
                });
#pragma warning restore 612, 618
        }
    }
}
